# Generated by Django 4.1.5 on 2023-01-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_calorie_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='calorie_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=7),
        ),
    ]
