# Generated by Django 4.1.5 on 2023-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0002_alter_fooditem_calorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calorie',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
    ]
