# Generated by Django 4.1.5 on 2023-01-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0003_alter_fooditem_calorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodconsumed',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
