# Generated by Django 4.1.5 on 2023-01-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0005_remove_fooditem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
