# Generated by Django 4.1.5 on 2023-01-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0006_fooditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
