# Generated by Django 4.1.5 on 2023-01-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calories', '0008_remove_fooditem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodconsumed',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
